source 'https://github.com/CocoaPods/Specs.git'
platform :osx, '10.12'
use_frameworks!

target 'Typora' do
  pod 'Sparkle'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '5.2.1'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
  config.build_settings["ONLY_ACTIVE_ARCH"] =
  "NO"
  end
end
